global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["192.168.1.14:8080"]
    authorization:
      credentials: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwcm9tZXRoZXVzQGV4LmNvbSIsImlhdCI6MTc0NjAxMjAxMiwiZXhwIjoyMDA1MjEyMDEyfQ.HI1ZKuyhNgELRUpRIZNcX7GeqiW9B4tro1qugAoaLcrEkKQ7O2BCIslrRVNlB0HKIsnCABpDSgCLf3CW9HFRWQ"



